/* import shared library */
@Library('jenkins-shared-libs') _


pipeline {
    agent {
      node {
        // spin up a pod to run this build on
        label 'docker'
      }
    }
 

   options {
        timeout(time: 45, unit: 'MINUTES')
    }
    stages {

        stage('what to do') {
            sh('git show-ref --tags > tags')
    def tags = readFile('tags').trim()
    def userInput = input([ message: 'Please select git tag', parameters: [[$class: 'ChoiceParameterDefinition', choices: tags, description: '', name: 'Tag']]])

    echo ("selected tag: "+userInput)
    def sha1 = userInput.split(' ')[0]
    echo ("selected sha1: "+ sha1)
            steps {
echo moo

    

            }
        stage('Build docker image') {

            steps {
            echo moo    
            }
        }
        stage('Approve') {
            steps {
                input message: "Do you want to approve the deploy in production?", id: "approval"
                sh 'make -f ./openshift/Makefile approved'
            }
        }
        stage('Tag PRD') {
            steps {
                sh 'make -f ./openshift/Makefile tag-prd'
            }
        }
        stage('Deploy PRD') {
            steps {
                sh 'make -f ./openshift/Makefile deploy-prd'
            }
        }
    }
    post {
        always {
            sh 'make -f ./openshift/Makefile post-clean'
            cleanWs()
        }
    }
}
}
